server:
    port: 8082

spring:
  application:
    name: HOTEL-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/hotelmicroservices

  config:
    import: configserver:http://localhost:8085
