server:
  port: 8083

spring:
  application:
    name: RATING-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/ratingmicroservices

  config:
    import: configserver:http://localhost:8085
